feature: Adds custom git hooks Required to improve code quality Custom hooks for SWW commit template, automatic code testing, generating JsDoc, fixing and displaying lint errors, avoid pushing, merging and commiting to master

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e # using the options command to abort script at first error
 echo
 echo "PRE-COMMIT"
 
 EMAIL=$(git config user.email)
-
 # make sure the user has registered a valid university email address
 if [[ $EMAIL != *"@coventry.ac.uk" ]]; then
 	echo "  invalid config settings"
@@ -15,7 +14,6 @@ if [[ $EMAIL != *"@coventry.ac.uk" ]]; then
 	echo "    $ git config user.name 'zzz'"
 	echo "  where 'xxx' is your university username"
 	echo "  and 'zzz' is your name as it appears on your university ID badge"
-	echo
 	exit 1
 fi
 
@@ -43,34 +41,38 @@ if [ "$branch" = "master" ]; then
 	exit 1 # commit will not execute
 fi
 
-# is the current branch a direct child of the master branch?
-# echo "checking parent branch"
-# PARENT=$(git show-branch -a | grep -v `git rev-parse --abbrev-ref HEAD` | grep -v origin | sed 's/.*\[\(.*\)\].*/\1/' | grep -v -e '^$' | grep -v "^----$"
-# echo "parent branch is $PARENT")
-
-# see if the user is trying to commit to the master branch
-# echo "  you are trying to commit to the '$branch' branch"
-# if [ "$branch" = "master" ]; then
-#   echo "    you can't commit directly to the master branch"
-#   echo "    create a local feature branch first"
-#   echo
-#   exit 1
+# # Enforce commit style
+# messagecheck=`echo $gitmessage | grep -w "feat\|fix\|docs\|breaking"`
+# if [ -z "$messagecheck" ]
+# then 
+# 			echo "Your commit message must begin with one of the following"
+# 			echo "  feat(feature-name)"
+# 			echo "  fix(fix-name)"
+# 			echo "  docs(docs-change)"
+# 			echo " "
 # fi
 
 # check for valid branch name:
+local_branch="$(git rev-parse --abbrev-ref HEAD)"
+valid_branch_regex="^(feature|chore|fix)\/[a-z0-9._-]+$"
+if [[ ! $local_branch =~ $valid_branch_regex ]]
+then
+    echo "invalid branch name"
+    echo "branch name should be (feature|fix|chore)/commit message"
+		echo "e.g. fix/nasty-bug"
+		echo "please rename your branch and try again."
+    exit 1
+fi
 
-# valid_branch_regex="^iss\d{3}\/[a-z\-]+$"
+echo 'Checking code style and fixing errors...'
 
-# if [[ ! $local_branch =~ $valid_branch_regex ]]
-# then
-#     echo "invalid branch name"
-#     echo "  format is: 'iss000/issue-name'"
-#     echo "  replacing '000' with the issue number and 'issue-name' with the issue name"
-#     echo "  only lower-case letters and replace spaces in the issue name with dashes"
-#     echo "  rename your branch and try again"
-#     exit 1
-# fi
+./node_modules/.bin/eslint . --fix
 
-./node_modules/.bin/eslint .
+echo 'Running test suites...'
+./node_modules/.bin/ava
 
-echo "  commit successful..."
+echo 'Generating JsDoc...'
+
+./node_modules/.bin/jsdoc -c jsdoc.conf
+
+echo "All good! Commit was successful 😎"
diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # With thanks to Sergio Vaccaro <sergio.vaccaro@istat.it>
 
@@ -12,26 +12,42 @@ PROTECTED_BRANCH="master"
 # Remote
 REMOTE=""
 
-# Check for merges
-if [[ $2 != 'merge' ]]; then
-    # Not a merge
-    ECHO "  not a merge"
-    exit 0
-fi
+# # Check for merges
+# if [[ $2 != 'merge' ]]; then
+#     # Not a merge
+#     echo "  not a merge"
+#     exit 0
+# fi
 
 # Current branch
 CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
 # Check if in PROTECTED_BRANCH
-#if [[ "$CURRENT_BRANCH" != "$PROTECTED_BRANCH" ]]; then
-#    # Not in PROTECTED_BRANCH: can proceed
-#    ECHO "  not in the ${PROTECTED_BRANCH} branch"
-#    exit 0
-#fi
+if [[ "$CURRENT_BRANCH" = "$PROTECTED_BRANCH" ]]; then
+   # In PROTECTED_BRANCH: can't proceed
+   echo "You're trying to push to ${PROTECTED_BRANCH} branch"
+   echo "Aborting. Open a pull request instead."
+   exit 1
+fi
 
-echo "  you are trying to merge into the ${PROTECTED_BRANCH} branch"
-echo "  merging branches to master must be done by creating a pull request"
-echo "  this merge has been cancelled however you will need to"
-echo "  reset the operation before continuing by running git reset --merge"
-echo
-exit 1
+
+# Enforce SWW commit template
+ORIG_MSG_FILE="$1"
+TEMP=`mktemp /tmp/git-XXXXX`
+exec < /dev/tty
+echo "Please enter type of commit (fix/feature/chore):"
+read TYPE
+echo "Please enter short summary of the commit:"
+read SUMMARY
+echo "Please enter why the commit is needed:"
+read WHY
+echo "Please enter what the commit does:"
+read WHAT
+
+MESSAGE="$TYPE: $SUMMARY
+$WHY
+$WHAT
+"
+
+(echo "$MESSAGE"; cat "$ORIG_MSG_FILE") > "$TEMP"
+cat "$TEMP" > "$ORIG_MSG_FILE"
